version: "3.8"

services:
  simulator:
    container_name: simulator
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8443:3000"
    restart: on-failure
    network_mode: host
    environment:
      SIMULATOR_URL: ${SIMULATOR_URL:-http://localhost:8443}
      EMAIL: ${EMAIL:-test@example.com}
      REDIRECT_URLS: ${REDIRECT_URLS:-http://localhost:3003/authenticate}
      POST_LOGOUT_REDIRECT_URLS: ${POST_LOGOUT_REDIRECT_URLS:-http://localhost:3003/post-logout}